include(${CMAKE_CURRENT_LIST_DIR}/Utils.cmake)

function(add_ruclient_to_target TARGET_NAME)
    if(RUCLIENT_ENABLED)
        set_target_properties(${TARGET_NAME} PROPERTIES CXX_STANDARD 20)
        target_compile_definitions(${TARGET_NAME} PRIVATE RUCLIENT_ENABLED)
        target_sources(${TARGET_NAME} PRIVATE rawhash_ruclient.cpp)
        target_link_libraries(${TARGET_NAME} PRIVATE ont_device_client_LIB ru_method_LIB)
    endif()
endfunction()

function(setup_ruclient)
    if(RUCLIENT_ENABLED)
        if(NOT RUCLIENT_DIR)
            override_cached(RUCLIENT_DIR ${EXTERNAL_PROJECTS_BUILD_DIR}/ruclient)
        endif()
        set(RUCLIENT_SOURCE_DIR ${CMAKE_SOURCE_DIR}/extern/readuntil_fake)
        add_subdirectory(${RUCLIENT_SOURCE_DIR} ${RUCLIENT_DIR})
        include_directories(${RUCLIENT_SOURCE_DIR}/include)
    else()
        message(STATUS "ruclient disabled")
    endif()
endfunction()
