function(setup_ccache_mold)
    if(USE_CCACHE)
        find_program(CCACHE_PROGRAM ccache)
        if(CCACHE_PROGRAM)
            message(STATUS "ccache found: ${CCACHE_PROGRAM}")
            set(CMAKE_C_COMPILER_LAUNCHER "${CCACHE_PROGRAM}")
            set(CMAKE_CXX_COMPILER_LAUNCHER "${CCACHE_PROGRAM}")
        else()
            message(WARNING "ccache not found, using default compiler")
        endif()
    endif()

    if(USE_MOLD)
        find_program(MOLD_PROGRAM mold)
        if(MOLD_PROGRAM)
            message(STATUS "mold found: ${MOLD_PROGRAM}")
            set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -fuse-ld=${MOLD_PROGRAM}")
        else()
            message(WARNING "mold not found, using default linker")
        endif()
    endif()
endfunction()
